{
 "title": "Azimuth / Identity",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Total realms",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(azimuth_identity_realm_phase)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total platforms",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(azimuth_identity_platform_phase)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total platform services",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(azimuth_identity_platform_service)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ready realms",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(azimuth_identity_realm_phase{phase=\"Ready\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unhealthy realms",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(azimuth_identity_realm_phase{phase!=\"Ready\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ready platforms",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(azimuth_identity_platform_phase{phase=\"Ready\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unhealthy platforms",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(azimuth_identity_platform_phase{phase!=\"Ready\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active services",
   "type": "stat",
   "description": "The number of services with at least one Zenith client.",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(azimuth_identity_platform_service_active_clients > bool 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Inactive services",
   "type": "stat",
   "description": "The number of services with no Zenith clients.",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(azimuth_identity_platform_service_active_clients == bool 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Realms by phase",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(azimuth_identity_realm_phase{phase=\"Ready\"}) or vector(0)",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(azimuth_identity_realm_phase{phase=\"Failed\"}) or vector(0)",
     "legendFormat": "Failed"
    },
    {
     "expr": "sum(azimuth_identity_realm_phase{phase=\"Pending\"}) or vector(0)",
     "legendFormat": "Pending"
    },
    {
     "expr": "sum(azimuth_identity_realm_phase{phase=\"Deleting\"}) or vector(0)",
     "legendFormat": "Deleting"
    },
    {
     "expr": "sum(azimuth_identity_realm_phase{phase!~\"Ready|Failed|Pending|Deleting\"}) or vector(0)",
     "legendFormat": "Unknown"
    }
   ]
  },
  {
   "title": "Platforms by phase",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 14, "x": 10, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(azimuth_identity_platform_phase{phase=\"Ready\"}) or vector(0)",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(azimuth_identity_platform_phase{phase=\"Failed\"}) or vector(0)",
     "legendFormat": "Failed"
    },
    {
     "expr": "sum(azimuth_identity_platform_phase{phase=\"Pending\"}) or vector(0)",
     "legendFormat": "Pending"
    },
    {
     "expr": "sum(azimuth_identity_platform_phase{phase=\"Updating\"}) or vector(0)",
     "legendFormat": "Updating"
    },
    {
     "expr": "sum(azimuth_identity_platform_phase{phase=\"Deleting\"}) or vector(0)",
     "legendFormat": "Deleting"
    },
    {
     "expr": "sum(azimuth_identity_platform_phase{phase!~\"Ready|Failed|Pending|Updating|Deleting\"}) or vector(0)",
     "legendFormat": "Unknown"
    }
   ]
  },
  {
   "title": "Realms",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "label_join(azimuth_identity_realm_phase, \"realm\", \"/\", \"realm_namespace\", \"realm_name\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(label_join(azimuth_identity_platform_phase, \"realm\", \"/\", \"platform_namespace\", \"realm_name\")) by(realm)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Platforms",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "label_join(azimuth_identity_platform_phase, \"platform\", \"/\", \"platform_namespace\", \"platform_name\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(label_join(azimuth_identity_platform_service, \"platform\", \"/\", \"platform_namespace\", \"platform_name\")) by(platform)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Platform services",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "label_join(azimuth_identity_platform_service, \"platform\", \"/\", \"platform_namespace\", \"platform_name\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "azimuth_identity_platform_service_active_clients",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}